import { Stand } from './stand.model';

export const STANDS: Stand[] = [
  {
    id: 1,
    name: 'Star Platinum',
    owner: 'Jotaro Kujo',
    part: 'Stardust Crusaders',
    ability: 'Star Finger',
    isKey: true,
    avatarUrl: '../../assets/img/star-platium.png',
    descrShort: `Jotaro has described Star Platinum as very violent. It is silent, except when it throws punches, during which it cries "ORAORAORA" loudly and repeatedly. With a relatively human face, it may scowl and smile. It has a very malicious grin when it is first revealed.`,
    descrLong: `It is one of the most powerful Stands featured in the series. Its overwhelming physical prowess in every basic characteristic, save for range, coupled with Jotaro's own cleverness in combat, allows Jotaro to repeatedly prevail against many Stand users even without the usage of any special ability. In addition, Jotaro's discovery of its time-stopping ability only made it all the more formidable in combat.`,
  },
  {
    id: 2,
    name: 'Crazy Diamond',
    owner: 'Josuke Higashikata',
    part: 'Diamond is Unbreakable',
    ability: 'Restoration',
    isKey: true,
    avatarUrl: '../../assets/img/crazy-diamond.png',
    descrShort: `Crazy Diamond is a Close-Range Stand, which like Jotaro Kujo's Star Platinum, is characterized by its physical might and speed at the cost of a short range of 2 meters. `,
    descrLong: `Crazy Diamond is a powerful Stand in close-quarter combat whose capabilities are enhanced by its unconventional power of repairing broken items, making it a redoubtable and unpredictable Stand in a fight, but also an invaluable fighting partner as it can effectively heal any wound.`,
  },
  {
    id: 3,
    name: 'Gold Experience',
    owner: 'Giorno Giovanna',
    part: 'Vento Aureo',
    ability: 'Life Giver',
    isKey: true,
    avatarUrl: '../../assets/img/gold-experience.png',
    descrShort: `Gold Experience is a close-range Stand, with a range of 2 meters from its user. Relative to other similar Stands such as Star Platinum or Crazy Diamond, Gold Experience isn't very strong. Despite this, it is rather fast and capable of easily destroying vehicles such as cars and motorcycles. It also does the occassional kick, similar to The World. Gold Experience does, however, possess a very versatile power.`,
    descrLong: `By infusing life energy in an inorganic object, Gold Experience can transform said object into a living organism of Giorno’s choosing, be it an animal or a plant. For instance, it can transform a piece of luggage into a frog, or a lighter into a rose.[3] The lifeforms can persist for a long time and even at a significant distance away from Giorno. It can also freely cancel this effect and return an object to its original inorganic state.`,
  },
  {
    id: 4,
    name: 'Stone Free',
    owner: 'Joyline Kujo',
    part: 'Stone Ocean',
    ability: 'String Decomposition',
    isKey: true,
    avatarUrl: '../../assets/img/stone-free.png',
    descrShort: `Stone Free is a unique close-range Stand that can not only be summoned to fight, but also provides Jolyne with integrated abilities. Like her father's Star Platinum, Jolyne's Stone Free is both powerful and fast, making it great for fighting physically.`,
    descrLong: `Stone Free is a unique close-range Stand that can not only be summoned to fight, but also provides Jolyne with integrated abilities. Like her father's Star Platinum, Jolyne's Stone Free is both powerful and fast, making it great for fighting physically. Moreover, its string power gives it great versatility that allows Jolyne a wide array of actions in combat.
        When Stone Free's string is completely wound or compacted, it is very strong; the destructive force of its punch roughly equivalent to that exerted by a small, extremely fast meteor. It is also fast enough to deflect several bullets aimed at it.`,
  },
  {
    id: 5,
    name: 'Silver Chariot',
    owner: 'Jean Pierre Polnareff',
    part: 'Stardust Crusaders',
    ability: 'Shooting the Sword',
    isKey: false,
    avatarUrl: '../../assets/img/silver-chariot.png',
    descrShort: `Silver Chariot is a powerful, battle-dedicated close-range Stand that primarily fights with the rapier it is equipped with.`,
    descrLong: `All its powers directly assist the Stand in battle but have limited use anywhere else. It is an incredibly agile Stand, able to attack enemies with barrages of sword slashes and thrusts before the opponent can react. It can also use this agility, along with its sword, to defend and deflect attacks aimed at it or its user. Silver Chariot usually doesn't stray far away from Polnareff, but still had the ability to move several meters away from him to attack.`,
  },
  {
    id: 6,
    name: `Magician's Red`,
    owner: 'Muhammad Avdol',
    part: 'Stardust Crusaders',
    ability: 'Pyrokinesis',
    isKey: false,
    avatarUrl: '../../assets/img/magicians-red.png',
    descrShort: `Magician's Red is a powerful Stand with an advantage in range thanks to its ability to manipulate fire. Moreover, Magician's Red is still a physically powerful Stand, a single kick of his being able to shatter Judgement's armor, whereas Silver Chariot couldn't.`,
    descrLong: `Magician's Red is capable of generating flames intense enough to evaporate metal projectiles mid-air and slice railroad tracks. Moreover, Magician's Red's flames are not ordinary flames but can be freely manipulated by Avdol. With a thought, the seer can redirect his flames mid-air, give them any shape, control how intense their destructive power is, and even give them other supernatural properties.`,
  },
  {
    id: 7,
    name: 'The World',
    owner: 'Dio Brando',
    part: 'Stardust Crusaders',
    ability: 'Time Stop',
    isKey: false,
    avatarUrl: '../../assets/img/the-world.png',
    descrShort: `The World is an exceptionally powerful Close-range Stand much like Star Platinum as noted by Noriaki Kakyoin and Jotaro Kujo, but boasting an effective manifestation range of approximately 10 meters.`,
    descrLong: `The World is an exceptionally powerful Close-range Stand much like Star Platinum as noted by Noriaki Kakyoin and Jotaro Kujo, but boasting an effective manifestation range of approximately 10 meters. Despite requiring a close distance to inflict damage, its overwhelming physical might and near unstoppable control over time undeniably make it one of the most dangerous Stands in the entire series.`,
  },
  {
    id: 8,
    name: 'The Hand',
    owner: 'Okuyasu Nijimura',
    part: 'Diamond is Unbreakable',
    ability: 'Elimination',
    isKey: false,
    avatarUrl: '../../assets/img/the-hand.png',
    descrShort: `The Hand is a heavily battle-oriented Stand. Similarly to Crazy Diamond, The Hand is a powerful short-ranged Stand who can easily wrestle with the former, although it is not as fast. The Hand’s power is very similar to that of Cream.`,
    descrLong: `The Hand is a heavily battle-oriented Stand. Similarly to Crazy Diamond, The Hand is a powerful short-ranged Stand who can easily wrestle with the former, although it is not as fast. The Hand’s power is very similar to that of Cream.

    Its unique power of space erasure makes it theoretically one of the strongest Stands of Diamond is Unbreakable, but as Josuke points out, Okuyasu's slow wit dampens its potential.`,
  },
  {
    id: 9,
    name: 'Killer Queen',
    owner: 'Yoshikage Kira',
    part: 'Diamond is Unbreakable',
    ability: 'Bomb Transmutation',
    isKey: false,
    avatarUrl: '../../assets/img/killer-queen.png',
    descrShort: `Killer Queen is a short-range humanoid Stand of average to above-average speed and melee attacking power.`,
    descrLong: `Killer Queen's powers revolve around setting up different kinds of bombs that can annihilate Kira's enemies in one blast, making it a very dangerous Stand to face. Not only are the bombs powerful, but Kira is also able to deploy two initially, then eventually three kinds of bombs with different strengths, giving the serial-killer a large array of options when dealing with his foes.`,
  },
  {
    id: 10,
    name: 'Sticky Fingers',
    owner: 'Bruno Bucciarati',
    part: 'Vento Aureo',
    ability: 'Zippers',
    isKey: false,
    avatarUrl: '../../assets/img/sticky-fingers.png',
    descrShort: `Sticky Fingers is a close-range Stand whose excellent strength and speed make it suitable for direct combat. In addition, it possesses a very versatile ability in the form of its zippers.`,
    descrLong: `Sticky Fingers' primary ability is to create zippers on any surface it touches with its fist, which it can remotely open or close at its leisure. For example, Sticky Fingers can hit a wall, unzip it to create an opening and go through it, then close the zipper.`,
  },
  {
    id: 11,
    name: 'King Crimson',
    owner: 'Diavolo',
    part: 'Vento Aureo',
    ability: 'Time Erasure',
    isKey: false,
    avatarUrl: '../../assets/img/king-crimson.png',
    descrShort: `King Crimson is one of the more impressive Stands featured in the series. Both physically strong and possessing the ability to erase time and predict the future, King Crimson is described as invincible against all other Stands whose powers do not affect time.`,
    descrLong: `King Crimson is a powerful Stand able to punch through people's bodies or cleave them in a chop with significant ease. Unlike other melee-based Stand Users, Diavolo generally uses it to perform swift single attacks that are almost always fatal rather than painful barrages. `,
  },
  {
    id: 12,
    name: 'Kiss',
    owner: 'Ermes Costello',
    part: 'Stone Ocean',
    ability: 'Duplicating Stickers',
    isKey: false,
    avatarUrl: '../../assets/img/kiss.png',
    descrShort: `Kiss is a powerful close-range Stand who compensates its short range with its speed and physical strength, and its stickers whom Ermes uses cleverly, making it a good addition to Jolyne's team.`,
    descrLong: `Ermes receives this Stand after Gwess gives her Jolyne's amulet that she had picked up. She discovers it during her first medical care visit in prison after being pierced by the Arrow.`,
  },
  {
    id: 13,
    name: 'Weather Report',
    owner: 'Weather Report',
    part: 'Stone Ocean',
    ability: 'Weather Control',
    isKey: false,
    avatarUrl: '../../assets/img/weather-report.png',
    descrShort: `Weather Report is a versatile Stand possessing near-complete control over the weather. This powerful ability allows Weather Report a wide array of options during a fight either for offense or defense, and as a result, it is very capable in close-combat.`,
    descrLong: `Weather manipulates the surrounding atmosphere with his Stand, allowing him to freely summon several weather phenomenons like wind, rain, or lightning to his advantage. Weather Report has enough precision that it can create micro-climates, but also a range great enough that it can make it rain 30 km away.`,
  },
  {
    id: 14,
    name: 'Whitesnake',
    owner: 'Enrico Pucci',
    part: 'Stone Ocean',
    ability: 'Melt your Heart',
    isKey: false,
    avatarUrl: '../../assets/img/whitesnake.png',
    descrShort: `As a long-distance Stand, Whitesnake possesses an extended range (about 20 meters), allowing its user, Enrico Pucci, to act undetected within the boundaries of Green Dolphin Street Prison. `,
    descrLong: `As a long-distance Stand, Whitesnake possesses an extended range (about 20 meters), allowing its user, Enrico Pucci, to act undetected within the boundaries of Green Dolphin Street Prison. Despite this, it displays strength similar to that of close-range Stands and is capable of performing precise and deadly movements like stabbing Diver Down and Foo Fighters with its hands, due to having its own strong ego.`,
  },
];
